version: '3.8'

services:
  mysql:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: unifesspa
      MYSQL_DATABASE: loja
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: '1.0'   # opcional, meio núcleo
